version: "3.9"

services:
  yt_downloader:
    image: vsepike/yt_downloader:latest
    container_name: yt_downloader
    environment:
      HOST: "0.0.0.0"
      DOWNLOAD_DIR: /app/downloads
      MIKU_BASE: miku_bot:8080
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    ports:
      - "5005:5005"
    networks:
      app:

  miku_bot:
    image: vsepike/MikuBot:latest
    container_name: miku_bot
    env_file:
      - .env
    environment:
      DOWNLOADER_URL: yt_downloader:5005
      TELEGRAM_BOT__APITOKEN: $T_TOKEN
    depends_on:
      - yt_downloader
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./secrets/miku.session:/app/miku.session
      - ./db:/app/db
    ports:
      - "8080:8080"
    networks:
      app:

networks:
  app: